name: Deploy Preview
description: Update preview environment values in the gitops repo
author: amine7536

inputs:
  gitops-repo:
    description: Gitops repo in owner/repo format
    required: true
  gitops-token:
    description: GitHub token with write access to gitops repo
    required: true
  service-name:
    description: Service name (e.g. backend-1, backend-2, front)
    required: true
  head-ref:
    description: Branch name triggering the preview (github.head_ref)
    required: true
  commit-sha:
    description: Commit SHA to pin
    required: true
  pr-author:
    description: PR author login
    required: false
    default: ''
  pr-url:
    description: PR HTML URL
    required: false
    default: ''
  pr-number:
    description: PR number
    required: false
    default: ''
  timestamp:
    description: Timestamp for metadata (e.g. PR updated_at)
    required: false
    default: ''
  workflow-run-url:
    description: URL of the triggering workflow run
    required: false
    default: ''

runs:
  using: node20
  main: dist/index.js
